### ISSUE TITLE
Unable to rename in field editor

### ISSUE THREAD

**Issue by aninternetian** [gamesoftcraft/OmniCA#6]
I'm unable to change "untitled" to my own name
![image](https://github.com/user-attachments/assets/05de89a7-0b58-433a-b0b9-19bd46a57e94)

**Comment by Ystyr** [comment]
Fixed

**Comment by aninternetian** [comment]
![image](https://github.com/user-attachments/assets/51374a0f-0b7e-4fb4-ab51-0a3b2b87fb9b)
